In [1]:
import torch


In [2]:
m = torch.nn.Linear(784,4)

In [4]:
m.weight

Parameter containing:
tensor([[-0.0048, -0.0276,  0.0244,  ..., -0.0192, -0.0163, -0.0042],
        [ 0.0063, -0.0138, -0.0094,  ..., -0.0099,  0.0012, -0.0028],
        [ 0.0337,  0.0158, -0.0126,  ..., -0.0349, -0.0047, -0.0032],
        [-0.0132,  0.0004,  0.0299,  ...,  0.0170, -0.0230,  0.0156]],
       requires_grad=True)

In [7]:
m.weight.dtype

torch.float32

In [8]:
m.bias

Parameter containing:
tensor([ 0.0134,  0.0195,  0.0140, -0.0285], requires_grad=True)

In [2]:
x = torch.randn((1,3))

In [3]:
x

tensor([[-0.4146,  1.7147,  0.2690]])

In [4]:
x.size

<function Tensor.size>

In [5]:
x.size()

torch.Size([1, 3])

In [6]:
x.shape()

TypeError: 'torch.Size' object is not callable

In [7]:
x.shape

torch.Size([1, 3])

In [12]:
y = torch.nn.Linear(1,2)(x.T)

In [13]:
y.size()

torch.Size([3, 2])